version: '3'

services:
  dev-container: 
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    # ports:
    #   - 5000:5000
    #   - 5001:5001
    depends_on:
            - db
    command: sleep infinity

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      - "SA_PASSWORD=yourStrong(!)Password"
      - "ACCEPT_EULA=Y"
    ports:
      - 1433:1433
    volumes:
      - DevContainer-db:/var/opt/mssql

volumes:
  DevContainer-db:
    driver: local

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080